-- AlterTable
ALTER TABLE `driver` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `isPrimaryVehicle` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `vehicleIpvaMonth` VARCHAR(191) NULL,
    ADD COLUMN `vehicleIpvaYear` VARCHAR(191) NULL,
    ADD COLUMN `vehicleLicensingDate` VARCHAR(191) NULL,
    ADD COLUMN `vehicleMileage` VARCHAR(191) NULL;
